### PR TITLE
New Features: Infinite Nesting And Sub-menu Collapsing

### PR DESCRIPTION
**Pull request by lo-tp**
### New Features
- Infinite Nesting:

    Previously nesting is only possible for the first level. With this PR merged, that limit could be removed.
- Submenu Collapsing

    Menus with children in the left sidebar could now be collapsed to avoid clutter.
### Backward Compatibility
By setting `fontLine` option to true, both the appearance and the behavior should be untouched from the original code.

### CODE REVIEW

**Comment by lo-tp** [comment]
Hi @praveenweb,
Sorry to disturb you.
Could you please have a look at this PR?

Thanks very much

**Comment by praveenweb** [comment]
@lo-tp - Thanks for this PR 🎉 

I'm currently reviewing this. Sub menu collapsing works as expected. But there is a slight issue in ordering of items alphabetically. So just checking that and a couple of css fixes. Should be able to merge once i figure out these smaller issues.

**Comment by lo-tp** [comment]
Hi @praveenweb, thanks for your efforts in reviewing this PR.

It would be great if you can elaborate on the issues you are trying to solve so that I can provide help if necessary.

**Comment by darrenhaken** [comment]
This will be a brilliant item to add 👍

**Comment by praveenweb** [comment]
@lo-tp - I saw a couple of issues.

First, under a submenu, the order of items is not alphabetical. It is probably random. Would like to fix the sorting for that. 
Second, there were styling issues for the submenu down arrow svg when the heading of the submenu has a lot of characters.

I have attempted to fix this in this branch `lotp-check` branch. I still have one more issue to fix. That is with the ordering of index.md when it is not mentioned in `forcedNavOrder` config.

**Comment by lo-tp** [comment]
@praveenweb 
What is expected behavior when there is an `index.md` not existing in `forcedNavOrder` config?

**Comment by praveenweb** [comment]
@lo-tp - The expected behaviour is to not show the item on the left sidebar.

**Comment by lo-tp** [comment]
@praveenweb I added a new item in config named `sideBar/ignoreIndex`.
By setting it to true the user can hide the index.md relevant page in the sidebar.

**Comment by lo-tp** [comment]
Hi @praveenweb  Is there any plan to proceed this PR?

**Comment by praveenweb** [comment]
@lo-tp - Sorry about the delay. I have merged the PR now. Thanks for the fixes. 🎉 
Will update our tutorials with the updated functionalities. 😄

**Pull request merged**
